const cars = [
  {
    id: 1,
    name: "BMW",
    price: 100,
    image: "images/bmw.jpeg",
    type: "sedan",
    rating: "3",
  },
  {
    id: 2,
    name: "Audi",
    price: 200,
    image: "images/audi.jpeg",
    type: "sedan",
    rating: "5",
  },
  {
    id: 3,
    name: "Mercedes",
    price: 300,
    image: "images/mercedes.jpeg",
    type: "sedan",
    rating: "2",
  },
  {
    id: 4,
    name: "Swift",
    price: 100,
    image: "images/swift.jpeg",
    type: "hatchback",
    rating: "4",
  },
  {
    id: 5,
    name: "Honda",
    price: 200,
    image: "images/honda.jpeg",
    type: "sedan",
    rating: "5",
  },
  {
    id: 6,
    name: "Ford",
    price: 300,
    image: "images/ford.jpeg",
    type: "sedan",
    rating: "4.5",
  },
  {
    id: 7,
    name: "Maruti WagonR",
    price: 100,
    image: "images/wagonr.webp",
    type: "hatchback",
    rating: "4.5",
  },
];
module.exports.cars = cars;
